name: diana_lc_front
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  sqflite: ^2.2.8+4
  path_provider: ^2.1.2
  path: ^1.9.0
  http: ^1.1.0  # â† Nueva dependencia agregada
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/logo_diana.png